apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-blob-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: custom-azureblobfuse
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: wizstudio-data
    volumeAttributes:
      containerName: data
      storageAccount: wizstudio
    nodeStageSecretRef:
      name: azure-blob-secret
      namespace: default
